# 自動生成するものを除外
AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/migrate/*.rb"

# 文字制限
Metrics/LineLength:
  Max: 160

# 「includeは文頭に書く」を除外
Style/MixinUsage:
  Exclude:
    - 'bin/**/*'

# ドキュメント用のコメントを不要とする
Style/Documentation:
  Enabled: false

# 日本語のコメントを制限しない
Style/AsciiComments:
  Enabled: false

# ダブルクオートをデフォルトにする
Style/StringLiterals:
  EnforcedStyle: double_quotes

# RSpecの行数を制限しない
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
